//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTrackingServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerComment
    {
        public int ManagerCommentID { get; set; }
        public string Comments { get; set; }
        public Nullable<int> ProjectTaskID { get; set; }
    
        public virtual ProjectTask ProjectTask { get; set; }
    }
}
