//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTrackingServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStory
    {
        public UserStory()
        {
            this.ProjectTasks = new HashSet<ProjectTask>();
        }
    
        public int UserStoryID { get; set; }
        public string Story { get; set; }
        public Nullable<int> ProjectID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<ProjectTask> ProjectTasks { get; set; }
    }
}
